# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3572c8c39c0330b2ecf21a4528b20f574fa22c8c664576cea40f8b9790157203de2797e1b0f16b402f6279d7b0ba42ebbfd9b5c6a26c0d05f4ee220d41dd854f

test:
  secret_key_base: eb55bf73dbff943e41bb2151675f34d0e61dec79946c6370af42e509a8299d8d1938dd25017a2383d15dfd595829366df253a4828ce555fc39fb663484118869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
